# .github/FUNDING.yml
# Version: v1.4.0
# Last update: 2025-06-13

# Enable GitHub Sponsors button
github: YENTERTAINR01

# (Optional, you can uncomment later if needed:)
# patreon: your_patreon_username
# open_collective: your_open_collective_username
# ko_fi: your_kofi_username
# buy_me_a_coffee: your_bmc_username
# custom: ['https://your-custom-donation-link.com']
