base:
  platform: shopee
  category: 通货
  output_dir: output
  input_glob: table_1*.csv
  numeric_cols:
    - 本期采购价
    - 国内运费
    - 国际运费
    - 仓库操作费
  common_path_template:
    trend_keyword_file: config/trend_keywords/trend_keywords_{code}.txt
    input_dir: input/raw_data_{code}
    market_rule_table_csv: config/market_rules/market_rule_config_{code}.csv

markets:
  - code: ID
  - code: TH
  - code: MY
  - code: VN
  - code: SG
  - code: PH
  - code: HK
  - code: MO
  - code: TW

last_run_date: "2025-06-18"
