# status_config.yaml 配置文件
# 🚀 用于 run_selection_analysis.py 配置运营规则

# ===================
# ✅ 1️⃣ status_keep
# 运营逻辑中 “可发货” 的产品状态 → 用于筛选活跃产品
# 后续如果有新增状态，需要同步补充
# ===================
status_keep:
  - 正常备货
  - 清库存

# ===================
# ✅ 2️⃣ status_category_mapping
# 将产品状态映射为 “产品状态分类” 字段 → 主要用于运营报告/上新表
# ===================
status_category_mapping:
  正常备货: 主力上新
  清库存: 礼包SKU（礼包可用）
  礼品: 礼包SKU（礼包专用）
  自由定价: 人工确认
  下架: 人工确认

# ===================
# ✅ 3️⃣ operate_advice_mapping
# 将产品状态映射为 “运营上架建议” 字段 → 主要用于选品优先级表/供运营同学参考
# ===================
operate_advice_mapping:
  正常备货: 推荐上架（上架价 ≥ 最低价，禁止低价违规）
  清库存: 暂不推荐上架（当前阶段不做礼包促销）
  礼品: 暂不推荐上架（当前阶段不做礼包促销）
  自由定价: 可上架（需手动确认最低价合规）
  下架: 暂不推荐上架

# ===================
# ✅ 4️⃣ future_reserved
# 预留字段 → 后续如果要扩展别的 mapping，可以加在这里
# 目前暂时保留为空
# ===================
future_reserved: {}
